name: glcgate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  connectivity_plus: ^6.1.0
  dio: ^5.8.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.1.1
  flutter_staggered_animations: ^1.1.1
  haptic_feedback: ^0.6.4+2
  iconsax_flutter: ^1.0.1
  loading_animation_widget: ^1.3.0
  lottie: ^3.1.2
  package_info_plus: ^8.0.0
  shared_preferences: ^2.3.0
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
