name: glcgate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  loading_animation_widget: ^1.3.0
  dio: ^5.8.0
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0
  collection: ^1.18.0
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.1.0
  package_info_plus: ^8.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
